# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui/lineup.ui'
#
# Created: Thu Jan 22 22:54:42 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(311, 194)
        self.blue_top = QtGui.QComboBox(Form)
        self.blue_top.setGeometry(QtCore.QRect(10, 10, 131, 22))
        self.blue_top.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.blue_top.setObjectName("blue_top")
        self.blue_top.addItem("")
        self.purple_top = QtGui.QComboBox(Form)
        self.purple_top.setGeometry(QtCore.QRect(170, 10, 131, 22))
        self.purple_top.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.purple_top.setObjectName("purple_top")
        self.purple_top.addItem("")
        self.blue_mid = QtGui.QComboBox(Form)
        self.blue_mid.setGeometry(QtCore.QRect(10, 70, 131, 22))
        self.blue_mid.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.blue_mid.setObjectName("blue_mid")
        self.blue_mid.addItem("")
        self.purple_mid = QtGui.QComboBox(Form)
        self.purple_mid.setGeometry(QtCore.QRect(170, 70, 131, 22))
        self.purple_mid.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.purple_mid.setObjectName("purple_mid")
        self.purple_mid.addItem("")
        self.blue_jungle = QtGui.QComboBox(Form)
        self.blue_jungle.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.blue_jungle.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.blue_jungle.setObjectName("blue_jungle")
        self.blue_jungle.addItem("")
        self.purple_jungle = QtGui.QComboBox(Form)
        self.purple_jungle.setGeometry(QtCore.QRect(170, 40, 131, 22))
        self.purple_jungle.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.purple_jungle.setObjectName("purple_jungle")
        self.purple_jungle.addItem("")
        self.blue_adc = QtGui.QComboBox(Form)
        self.blue_adc.setGeometry(QtCore.QRect(10, 100, 131, 22))
        self.blue_adc.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.blue_adc.setObjectName("blue_adc")
        self.blue_adc.addItem("")
        self.purple_adc = QtGui.QComboBox(Form)
        self.purple_adc.setGeometry(QtCore.QRect(170, 100, 131, 22))
        self.purple_adc.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.purple_adc.setObjectName("purple_adc")
        self.purple_adc.addItem("")
        self.blue_support = QtGui.QComboBox(Form)
        self.blue_support.setGeometry(QtCore.QRect(10, 130, 131, 22))
        self.blue_support.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.blue_support.setObjectName("blue_support")
        self.blue_support.addItem("")
        self.purple_support = QtGui.QComboBox(Form)
        self.purple_support.setGeometry(QtCore.QRect(170, 130, 131, 22))
        self.purple_support.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.purple_support.setObjectName("purple_support")
        self.purple_support.addItem("")
        self.set_button = QtGui.QPushButton(Form)
        self.set_button.setGeometry(QtCore.QRect(10, 160, 291, 23))
        self.set_button.setObjectName("set_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.blue_top, self.purple_top)
        Form.setTabOrder(self.purple_top, self.purple_jungle)
        Form.setTabOrder(self.purple_jungle, self.blue_jungle)
        Form.setTabOrder(self.blue_jungle, self.blue_mid)
        Form.setTabOrder(self.blue_mid, self.purple_mid)
        Form.setTabOrder(self.purple_mid, self.purple_adc)
        Form.setTabOrder(self.purple_adc, self.blue_adc)
        Form.setTabOrder(self.blue_adc, self.blue_support)
        Form.setTabOrder(self.blue_support, self.purple_support)
        Form.setTabOrder(self.purple_support, self.set_button)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Lineups", None, QtGui.QApplication.UnicodeUTF8))
        self.blue_top.setItemText(0, QtGui.QApplication.translate("Form", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.purple_top.setItemText(0, QtGui.QApplication.translate("Form", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.blue_mid.setItemText(0, QtGui.QApplication.translate("Form", "Mid", None, QtGui.QApplication.UnicodeUTF8))
        self.purple_mid.setItemText(0, QtGui.QApplication.translate("Form", "Mid", None, QtGui.QApplication.UnicodeUTF8))
        self.blue_jungle.setItemText(0, QtGui.QApplication.translate("Form", "Jungle", None, QtGui.QApplication.UnicodeUTF8))
        self.purple_jungle.setItemText(0, QtGui.QApplication.translate("Form", "Jungle", None, QtGui.QApplication.UnicodeUTF8))
        self.blue_adc.setItemText(0, QtGui.QApplication.translate("Form", "ADC", None, QtGui.QApplication.UnicodeUTF8))
        self.purple_adc.setItemText(0, QtGui.QApplication.translate("Form", "ADC", None, QtGui.QApplication.UnicodeUTF8))
        self.blue_support.setItemText(0, QtGui.QApplication.translate("Form", "Support", None, QtGui.QApplication.UnicodeUTF8))
        self.purple_support.setItemText(0, QtGui.QApplication.translate("Form", "Support", None, QtGui.QApplication.UnicodeUTF8))
        self.set_button.setText(QtGui.QApplication.translate("Form", "Set lineup", None, QtGui.QApplication.UnicodeUTF8))

