# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui/teams.ui'
#
# Created: Thu Jan 22 22:54:37 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 413)
        self.formLayoutWidget = QtGui.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 311, 197))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.name = QtGui.QLineEdit(self.formLayoutWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.name)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.tag = QtGui.QLineEdit(self.formLayoutWidget)
        self.tag.setObjectName("tag")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tag)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.top = QtGui.QLineEdit(self.formLayoutWidget)
        self.top.setObjectName("top")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.top)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.mid = QtGui.QLineEdit(self.formLayoutWidget)
        self.mid.setObjectName("mid")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.mid)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.adc = QtGui.QLineEdit(self.formLayoutWidget)
        self.adc.setObjectName("adc")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.adc)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.support = QtGui.QLineEdit(self.formLayoutWidget)
        self.support.setObjectName("support")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.support)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.jungle = QtGui.QLineEdit(self.formLayoutWidget)
        self.jungle.setObjectName("jungle")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.jungle)
        self.load_button = QtGui.QPushButton(Form)
        self.load_button.setEnabled(False)
        self.load_button.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.load_button.setObjectName("load_button")
        self.save_button = QtGui.QPushButton(Form)
        self.save_button.setEnabled(False)
        self.save_button.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.save_button.setObjectName("save_button")
        self.set_blue_button = QtGui.QPushButton(Form)
        self.set_blue_button.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.set_blue_button.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.set_blue_button.setObjectName("set_blue_button")
        self.set_purple_button = QtGui.QPushButton(Form)
        self.set_purple_button.setGeometry(QtCore.QRect(100, 240, 75, 23))
        self.set_purple_button.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.set_purple_button.setObjectName("set_purple_button")
        self.clear_button = QtGui.QPushButton(Form)
        self.clear_button.setGeometry(QtCore.QRect(190, 240, 75, 23))
        self.clear_button.setObjectName("clear_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.name, self.tag)
        Form.setTabOrder(self.tag, self.top)
        Form.setTabOrder(self.top, self.jungle)
        Form.setTabOrder(self.jungle, self.mid)
        Form.setTabOrder(self.mid, self.adc)
        Form.setTabOrder(self.adc, self.support)
        Form.setTabOrder(self.support, self.load_button)
        Form.setTabOrder(self.load_button, self.save_button)
        Form.setTabOrder(self.save_button, self.set_blue_button)
        Form.setTabOrder(self.set_blue_button, self.set_purple_button)
        Form.setTabOrder(self.set_purple_button, self.clear_button)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Team roster", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Mid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "ADC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Support", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Jungle", None, QtGui.QApplication.UnicodeUTF8))
        self.load_button.setText(QtGui.QApplication.translate("Form", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.set_blue_button.setText(QtGui.QApplication.translate("Form", "Set blue", None, QtGui.QApplication.UnicodeUTF8))
        self.set_purple_button.setText(QtGui.QApplication.translate("Form", "Set purple", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_button.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))

